### ISSUE TITLE
Some question when set MSMT17 as target domain

### ISSUE THREAD

**Issue by HardWayShip** [SikaStar/Dual-Refinement#1]
Hi, Doc.Dai. 
When I reproduced your code. I found the README.md only shows how to run the code in the tasks of Duke 2 Market and Market 2 Duke. and the trained model in Google drive only contains Duke 2 Market and Market 2 Duke.

**If I want to set MSMT17 as a target domain, What pre-training model do I need to add？ （for example, duke 2 msmt17）or just run the dual_refine_train.py directly?**

looking forward to your answer, thanks a lot.

best wishes to you :)

**Comment by SikaStar** [comment]
> Hi, Doc.Dai. When I reproduced your code. I found the README.md only shows how to run the code in the tasks of Duke 2 Market and Market 2 Duke. and the trained model in Google drive only contains Duke 2 Market and Market 2 Duke.
> 
> **If I want to set MSMT17 as a target domain, What pre-training model do I need to add？ （for example, duke 2 msmt17）or just run the dual_refine_train.py directly?**
> 
> looking forward to your answer, thanks a lot.
> 
> best wishes to you :)

Hi,
When you conduct the experiments on Duke2MSMT and Market2MSMT, you can use the trained model in Google drive as well. The pre-trained model for Duke2MSMT is the same as Duke2Market.
