### ISSUE TITLE
Market/Duke到msmt上复现代码性能存在问题

### ISSUE THREAD

**Issue by chenyiyuu** [SikaStar/Dual-Refinement#2]
您好，感谢您的卓越工作。
我在复现您代码时候好像出了点问题，在msmt17上的性能在12%左右徘徊上不去，我并没有做什么更改，想问问您是哪里出了问题？
我跑代码的方式：
将sh文件的target换成msmt17，然后把iter改为800

**Comment by SikaStar** [comment]
> 您好，感谢您的卓越工作。 我在复现您代码时候好像出了点问题，在msmt17上的性能在12%左右徘徊上不去，我并没有做什么更改，想问问您是哪里出了问题？ 我跑代码的方式： 将sh文件的target换成msmt17，然后把iter改为800

你好，谢谢你对我们工作的关注。msmt性能比较低的情况可能是DBSCAN的聚类参数rho设置的比较大，你试试设为rho=0.7e-3。
